services:
  - type: web
    name: telegram-content-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        value: rv8AfdLoIH0xAqDDPc2hiXhevPyh672HRncOGN2p7EQ
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: WEBHOOK_HOST
        value: https://telegram-content-bot.onrender.com
      - key: WEBHOOK_PATH
        value: /webhook
      - key: ADMIN_ID
        value: "757179699"
      - key: SBP_PHONE
        value: "+79994206101"
      - key: SBP_BANK
        value: "ОЗОН"
      - key: SBP_NAME
        value: "Роман"
      - key: TRIAL_DAYS
        value: "7"
      - key: POSTS_PER_DAY_TRIAL
        value: "3"
      - key: POSTS_PER_DAY_SUBSCRIPTION
        value: "50"
      - key: SUBSCRIPTION_PRICE
        value: "990"
    healthCheckPath: /health
